// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cephei.Gen
{
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    using Cephei.Gen.Model;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Class : ClassBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
/* 
Name:           Interface.cst
Author:         Stephen Channell
Description:    Generate a single Interface for the Class
*/
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
  
     
    Context.ElementName = ElementName; 
    Context.RootName = RootPackageName;
    Context.Prefix = "I";
    Context.Suffix = "";
    Context.ClassDelimiter = ".";
    
    string Namespace = "Cephei." + Context.CurrentClass.GetNamespace (Context.ClassDelimiter).Replace ("QL", "Data");
    string DataNamespace = Namespace.Replace (".Data", ".Q");

    bool emptyClass = true;
    foreach(Method method in Context.CurrentClass.Methods)
    { 
        if (Context.Included2 (method, (method.Name == Context.CurrentClass.Name && !Context.CurrentClass.IsAbstract)) && !method.Name.StartsWith("operator") && !method.Name.StartsWith("~"))
        {
            emptyClass = false;
        }
    }
    if (emptyClass) 
    {

            
            #line default
            #line hidden
            this.Write(" \r\n//////////////////////////////////////////////////////////////////////////////" +
                    "////////////////////////////////////////////\r\n// Class ");
            
            #line 39 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(" does not have any exportable functions\r\n////////////////////////////////////////" +
                    "////////////////////////////////////////////////////////////////////////////////" +
                    "//\r\n\r\n");
            
            #line 42 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

//        return "";
    }
    if (Context.CurrentClass.FileName == "") return "";

            
            #line default
            #line hidden
            this.Write(@"using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using Cephei.Core;
using Cephei.Core.Generic;
using Cephei.Kernel;
using Microsoft.FSharp.Core;
using Cephei.");
            
            #line 56 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace (Context.ClassDelimiter)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 58 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tnamespace ");
            
            #line 60 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 62 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

    Parameter pricerParameter = Context.CurrentClass.PricingParameter ();
    bool haveRenderedBaseClass = false;

    foreach(Method method in Context.CurrentClass.Methods)
    { 
        if (Context.Included2 (method, (method.Name == Context.CurrentClass.Name && !Context.CurrentClass.IsAbstract)) && !method.Name.StartsWith("operator") && !method.Name.StartsWith("~"))
        {

            
            #line default
            #line hidden
            this.Write("        /* <summary>\r\n            ");
            
            #line 72 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Notes));
            
            #line default
            #line hidden
            this.Write(" \r\n            ");
            
            #line 73 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Notes));
            
            #line default
            #line hidden
            this.Write(" \r\n        </summary> */\r\n");
            
            #line 75 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            if (method.Name == Context.CurrentClass.Name)
            {
                if (!haveRenderedBaseClass && !method.IsNameUnique) 
                {
                    haveRenderedBaseClass = true;

            
            #line default
            #line hidden
            this.Write("        [DataContract (Name = \"");
            
            #line 82 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((DataNamespace + "." + method.Name)));
            
            #line default
            #line hidden
            this.Write("Base\", Namespace = Declarations.SchemaVersion)]\r\n        [Serializable]\r\n        " +
                    "[Guid (\"");
            
            #line 84 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Guid.Substring(Context.CurrentClass.Guid.Length -3, 2)  + Context.CurrentClass.Guid.Substring(3, Context.CurrentClass.Guid.Length -6) + Context.CurrentClass.Guid.Substring(1, 2)));
            
            #line default
            #line hidden
            this.Write("\"),ComVisible(true)]\r\n        [ShowWith (typeof(ShowableObject<");
            
            #line 85 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        [CellProxy (typeof(CellProxy<");
            
            #line 86 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        public class ");
            
            #line 87 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Base \r\n            : Cell<");
            
            #line 88 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n        {\r\n        }\r\n");
            
            #line 91 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
                    
                }

            
            #line default
            #line hidden
            this.Write("        [DataContract (Name = \"");
            
            #line 94 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((DataNamespace + "." + method.DataClassName)));
            
            #line default
            #line hidden
            this.Write("\", Namespace = Declarations.SchemaVersion)]\r\n        [Serializable]\r\n        [Sho" +
                    "wWith (typeof(ShowableObject<");
            
            #line 96 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        [CellProxy (typeof(CellProxy<");
            
            #line 97 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        public class ");
            
            #line 98 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell \r\n");
            
            #line 99 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

                if (haveRenderedBaseClass)
                {

            
            #line default
            #line hidden
            this.Write("            : ");
            
            #line 103 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Base \r\n");
            
            #line 104 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

                }
                else
                {

            
            #line default
            #line hidden
            this.Write("            : Cell<");
            
            #line 109 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 110 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

                }

            
            #line default
            #line hidden
            this.Write("            , IFormula<");
            
            #line 113 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n        {\r\n");
            
            #line 115 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

                if (pricerParameter != null)
                {

            
            #line default
            #line hidden
            this.Write("            public ICoCell<");
            
            #line 119 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pricerParameter.GetQualifiedType (true, ".", "I", "").Replace ("::", ".")));
            
            #line default
            #line hidden
            this.Write("> QL_Pricer;\r\n            [DataMember (Name = \"QL_Pricer\", IsRequired=true, EmitD" +
                    "efaultValue=false, Order = 98)]\r\n            public DataChoice<");
            
            #line 121 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pricerParameter.GetQualifiedType (true, ".", "I", "").Replace ("::", ".")));
            
            #line default
            #line hidden
            this.Write(", string, string> DataQL_Pricer\r\n            {\r\n                get\r\n            " +
                    "    {\r\n                    return CellHelper.ToChoice<");
            
            #line 125 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pricerParameter.GetQualifiedType (true, ".", "I", "").Replace ("::", ".")));
            
            #line default
            #line hidden
            this.Write(" > (QL_Pricer);\r\n                }\r\n                set\r\n                {\r\n     " +
                    "               this.QL_Pricer = CellHelper.ToCoCell<");
            
            #line 129 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pricerParameter.GetQualifiedType (true, ".", "I", "").Replace ("::", ".")));
            
            #line default
            #line hidden
            this.Write("> (Parent, value);\r\n                }\r\n            }\r\n");
            
            #line 132 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

                }
            }
            else
            {

            
            #line default
            #line hidden
            this.Write("        [DataContract (Name = \"");
            
            #line 138 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((DataNamespace + "." + Context.CurrentClass.Name + "." + method.DataClassName)));
            
            #line default
            #line hidden
            this.Write("\", Namespace = Declarations.SchemaVersion)]\r\n        [Serializable]\r\n        [Sho" +
                    "wWith (typeof(Showable");
            
            #line 140 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnType.ShowType));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 140 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnType.Source == "void" ? "I" + Context.CurrentClass.Name : method.ReturnType.GetQualifiedTypeWithoutCollection(false,".", "I", "").Replace("::", ".")));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        [CellProxy (typeof(CellProxy<");
            
            #line 141 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnType.Source == "void" ? "I" + Context.CurrentClass.Name : method.ReturnType.GetQualifiedType(false,".", "I", "").Replace("::", ".")));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        public class ");
            
            #line 142 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell \r\n            : Cell<");
            
            #line 143 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnType.Source == "void" ? "I" + Context.CurrentClass.Name : method.ReturnType.GetQualifiedType(false,".", "I", "").Replace("::", ".")));
            
            #line default
            #line hidden
            this.Write(">\r\n            , IFormula<");
            
            #line 144 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnType.Source == "void" ? "I" + Context.CurrentClass.Name : method.ReturnType.GetQualifiedType(false,".", "I", "").Replace("::", ".")));
            
            #line default
            #line hidden
            this.Write(">\r\n        {\r\n");
            
            #line 146 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

//        }

            
            #line default
            #line hidden
            this.Write("            public ICoCell<");
            
            #line 149 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 149 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n            [DataMember (Name = \"");
            
            #line 150 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("\", IsRequired = true, EmitDefaultValue = false, Order = 0)]\r\n            public D" +
                    "ataChoice<");
            
            #line 151 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(",string, string> Data");
            
            #line 151 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("\r\n            {\r\n                get\r\n                {\r\n                    retu" +
                    "rn CellHelper.ToChoice (this.");
            
            #line 155 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n                set\r\n                {\r\n                  " +
                    "  this.");
            
            #line 159 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(" = CellHelper.ToCoCell<");
            
            #line 159 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("> (_parent, value);\r\n                }\r\n            }\r\n");
            
            #line 162 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        }
        foreach (KeyValuePair<int, Parameter> pair in method.Parameters)
        {

            
            #line default
            #line hidden
            this.Write("            public ICoCell<");
            
            #line 167 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.ParameterType.GetQualifiedTypeWithoutOption((pair.Value.Default != ""), ".", "I", "").Replace ("::", ".")));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 167 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n            [DataMember (Name = \"");
            
            #line 168 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write("\", IsRequired = ");
            
            #line 168 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!pair.Value.IsOptional).ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(", EmitDefaultValue = false, Order = ");
            
            #line 168 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Pos + 1));
            
            #line default
            #line hidden
            this.Write(")]\r\n            public DataChoice<");
            
            #line 169 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.ParameterType.GetQualifiedTypeWithoutOption((pair.Value.Default != ""), ".", "I", "").Replace ("::", ".")));
            
            #line default
            #line hidden
            this.Write(", string, string> Data");
            
            #line 169 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write("\r\n            {\r\n                get\r\n                {\r\n                    retu" +
                    "rn CellHelper.ToChoice (this.");
            
            #line 173 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n                set\r\n                {\r\n                  " +
                    "  this.");
            
            #line 177 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 177 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.CellHelper.Replace ("::", ".")));
            
            #line default
            #line hidden
            this.Write(" (_parent, value);\r\n                }\r\n            }\r\n");
            
            #line 180 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        }

            
            #line default
            #line hidden
            this.Write(@"            public ICell With;
            [DataMember (Name = ""With"", IsRequired = false, EmitDefaultValue = false, Order = 99)]
            public DataChoice<object, string, string> DataWith
            {
                get
                {
                    return CellHelper.ToChoice (With);
                }
                set
                {
                    this.With = CellHelper.WithCell (_parent, value);
                }
            }
            
            /* <summary>
                ");
            
            #line 198 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Notes));
            
            #line default
            #line hidden
            this.Write(" \r\n                ");
            
            #line 199 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Notes));
            
            #line default
            #line hidden
            this.Write(" \r\n            </summary> */\r\n            public ");
            
            #line 201 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell () : base () \r\n            {\r\n                if (Parent != null)\r\n         " +
                    "           Parent.WriteLog \r\n                        ( LogType.Information\r\n    " +
                    "                    , ");
            
            #line 206 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((method.Id * 10) + 10000000 + 1));
            
            #line default
            #line hidden
            this.Write("\r\n                        , \"Cephei.Data\"\r\n                        , \"Create\"\r\n  " +
                    "                      , \"");
            
            #line 209 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell()\"\r\n                        );\r\n            }\r\n            /* <summary>\r\n   " +
                    "             ");
            
            #line 213 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Notes));
            
            #line default
            #line hidden
            this.Write(" \r\n                ");
            
            #line 214 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Notes));
            
            #line default
            #line hidden
            this.Write(" \r\n            </summary> */\r\n            public ");
            
            #line 216 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell (IModel parent, string Mnemonic ");
            
            #line 216 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((method.Parameters.Count > 0 || Context.CurrentClass.Name != method.Name ? "," : "")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 216 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GetCellParamConstructor("I", "", ".").Replace("::",".")));
            
            #line default
            #line hidden
            this.Write(", ICell With)\r\n            {\r\n                ");
            
            #line 218 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((method.Name != Context.CurrentClass.Name ? "this." + Context.CurrentClass.Name + " = " + Context.CurrentClass.Name + ";" : "")));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 219 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            foreach (KeyValuePair<int, Parameter> pair in method.Parameters)
            {

            
            #line default
            #line hidden
            this.Write("                    this.");
            
            #line 223 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 223 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 224 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            }
            if (pricerParameter != null && method.Name == Context.CurrentClass.Name)
            {

            
            #line default
            #line hidden
            this.Write("                    this.QL_Pricer = QL_Pricer;\r\n");
            
            #line 230 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            }

            
            #line default
            #line hidden
            this.Write(@"                    this.With = With;
                    _mnemonic = (Mnemonic.StartsWith (""!"") ? Mnemonic : ""!"" + Cephei.Generator.StripMnemonic (Mnemonic));
                    this.Parent = parent;
                    if (parent != null)
                    {
                        parent[_mnemonic] = this;
                        parent.WriteLog 
                            ( LogType.Information
                            , ");
            
            #line 241 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((method.Id * 10) + 10000000 + 2));
            
            #line default
            #line hidden
            this.Write("\r\n                            , \"Cephei.Data\"\r\n                            , \"Cre" +
                    "ate\"\r\n                            , \"");
            
            #line 244 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell(...)\"\r\n                            );\r\n                    }\r\n            }\r" +
                    "\n            public static ");
            
            #line 248 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell Create (IModel parent, string Mnemonic ");
            
            #line 248 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((method.Parameters.Count > 0 || Context.CurrentClass.Name != method.Name ? "," : "")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 248 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GetCellParamConstructor("I", "", ".").Replace("::",".")));
            
            #line default
            #line hidden
            this.Write(", ICell With)\r\n            {\r\n                return new ");
            
            #line 250 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell (parent, Mnemonic ");
            
            #line 250 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((method.Parameters.Count > 0 || Context.CurrentClass.Name != method.Name ? "," : "")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 250 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GetCellParamCallConstructor2("I", "", ".").Replace("::",".")));
            
            #line default
            #line hidden
            this.Write(", With);\r\n            }\r\n            public static ");
            
            #line 252 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell Create (IModel model, object[] objects)\r\n            {\r\n                retu" +
                    "rn new ");
            
            #line 254 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write("Cell (model, objects);\r\n            }\r\n            public ");
            
            #line 256 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnType.Source == "void" || Context.CurrentClass.Name == method.Name ? "I" + Context.CurrentClass.Name : method.ReturnType.GetQualifiedType(false,".", "I", "").Replace("::",".")));
            
            #line default
            #line hidden
            this.Write(" Invoke (Unit __u)\r\n            {\r\n");
            
            #line 258 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        if (method.Name == Context.CurrentClass.Name)
        {

            
            #line default
            #line hidden
            this.Write("                return ");
            
            #line 262 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace.Replace(".Data", ".Fun") + "." + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Create (");
            
            #line 262 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GetCellParamCall ("", "", ",")));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 263 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        }
        else
        {
            bool noParams = (method.Parameters.Count == 0 && method.IsNameUnique);

            
            #line default
            #line hidden
            this.Write(@"                if (With != null)
                {
                    if (With is IPreCell)
                    {
                        IPreCell pre = (IPreCell) With;
                        if (With is IPostCell)
                        {
                            IPostCell post = (IPostCell) With;

                            return post.AfterValue (pre.BeforeValue (");
            
            #line 278 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(").");
            
            #line 278 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 278 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(( noParams ? "" : "(" + method.GetCellParamCall ("", "", ",") + ")" )));
            
            #line default
            #line hidden
            this.Write(");\r\n                        }\r\n                        else\r\n                    " +
                    "        return pre.BeforeValue(");
            
            #line 281 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(").");
            
            #line 281 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 281 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(( noParams ? "" : "(" + method.GetCellParamCall ("", "", ",") + ")" )));
            
            #line default
            #line hidden
            this.Write(";\r\n                    }\r\n                    else if (With is IPostCell)\r\n      " +
                    "              {\r\n                        IPostCell post = (IPostCell) With;\r\n   " +
                    "                     return post.AfterValue (");
            
            #line 286 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Value.");
            
            #line 286 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 286 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(( noParams ? "" : "(" + method.GetCellParamCall ("", "", ",") + ")" )));
            
            #line default
            #line hidden
            this.Write(");\r\n                    }\r\n                }\r\n                return ");
            
            #line 289 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Value.");
            
            #line 289 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 289 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(( noParams ? "" : "(" + method.GetCellParamCall ("", "", ",") + ")" )));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 290 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        }

            
            #line default
            #line hidden
            this.Write("            }\r\n        \r\n            public ");
            
            #line 295 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.XLClassName));
            
            #line default
            #line hidden
            this.Write(@"Cell (IModel model, object[] objects)
            {
                string Mnemonic = (string)objects.GetValue (0);
                _mnemonic = (Mnemonic.StartsWith (""!"") ? Mnemonic : ""!"" + Cephei.Generator.StripMnemonic (Mnemonic));
                this.Parent = model;
");
            
            #line 300 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        int c = 1;
        if (Context.CurrentClass.Name != method.Name)
        {

            
            #line default
            #line hidden
            this.Write("                this.");
            
            #line 305 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(" = CellHelper.CellObject<");
            
            #line 305 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">(model, (string) objects.GetValue (");
            
            #line 305 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c++));
            
            #line default
            #line hidden
            this.Write("), \"");
            
            #line 305 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("\" );\r\n");
            
            #line 306 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        }

        foreach (KeyValuePair<int, Parameter> pair in method.Parameters)
        {

            
            #line default
            #line hidden
            this.Write("                this.");
            
            #line 312 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 312 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.CellHelper));
            
            #line default
            #line hidden
            this.Write(" (model, objects.GetValue (");
            
            #line 312 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c++));
            
            #line default
            #line hidden
            this.Write("), \"");
            
            #line 312 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write("\" );\r\n");
            
            #line 313 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        }
        if (pricerParameter != null && method.Name == Context.CurrentClass.Name)
        {

            
            #line default
            #line hidden
            this.Write("                this.QL_Pricer = CellHelper.CellObject<");
            
            #line 318 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pricerParameter.GetQualifiedType (true, ".", "I", "").Replace ("::", ".")));
            
            #line default
            #line hidden
            this.Write("> (model, objects.GetValue (");
            
            #line 318 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c++));
            
            #line default
            #line hidden
            this.Write("), \"QL_Pricer\" );\r\n");
            
            #line 319 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        }

            
            #line default
            #line hidden
            this.Write("                this.With = CellHelper.WithCell (model, objects.GetValue (");
            
            #line 322 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c));
            
            #line default
            #line hidden
            this.Write("));\r\n\r\n            }\r\n            public override string ToString ()\r\n           " +
                    " {\r\n");
            
            #line 327 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        if (method.Parameters.Count == 0)
        {
            if (method.Name == Context.CurrentClass.Name)
            {

            
            #line default
            #line hidden
            this.Write("                return \"");
            
            #line 333 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace.Replace(".Data", ".Fun") + "." + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Create ()\";\r\n");
            
            #line 334 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            }
            else
            {
                bool noParams = (method.Parameters.Count == 0 && method.IsNameUnique);

            
            #line default
            #line hidden
            this.Write(@"                if (With != null)
                {
                    if (With is IPreCell)
                    {
                        IPreCell pre = (IPreCell) With;
                        if (With is IPostCell)
                        {
                            IPostCell post = (IPostCell) With;
                            return post.AfterSource (pre.BeforeSource (Generator.LetMnemonic (");
            
            #line 348 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Mnemonic), \"");
            
            #line 348 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            
            #line 348 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(( noParams ? "" : "(" + method.GetCellParamCall ("", "", ",") + ")" )));
            
            #line default
            #line hidden
            this.Write("\"));\r\n                        }\r\n                        else\r\n                  " +
                    "          return pre.BeforeSource (Generator.LetMnemonic (");
            
            #line 351 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Mnemonic), \"");
            
            #line 351 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            
            #line 351 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(( noParams ? "" : "(" + method.GetCellParamCall ("", "", ",") + ")" )));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    }\r\n                    else if (With is IPostCell)\r\n    " +
                    "                {\r\n                        IPostCell post = (IPostCell) With;\r\n " +
                    "                       return post.AfterSource (Generator.LetMnemonic (");
            
            #line 356 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Mnemonic) + \".Value.");
            
            #line 356 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            
            #line 356 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(( noParams ? "" : "(" + method.GetCellParamCall ("", "", ",") + ")" )));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    }\r\n                }\r\n                return Generator.L" +
                    "etMnemonic (");
            
            #line 359 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Mnemonic) + \".Value.");
            
            #line 359 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            
            #line 359 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(( noParams ? "" : "(" + method.GetCellParamCall ("", "", ",") + ")" )));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 360 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            }
        }
        else
        {

            
            #line default
            #line hidden
            this.Write("                \r\n                var __v = new System.Tuple<System.Type,string>[" +
                    "] \r\n");
            
            #line 367 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            string tupleDelim = "{";
            foreach (KeyValuePair<int, Parameter> pair in method.Parameters)
            {

            
            #line default
            #line hidden
            this.Write("                \r\n                    ");
            
            #line 372 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tupleDelim));
            
            #line default
            #line hidden
            this.Write(" Generator.ValueTuple (");
            
            #line 372 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 372 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value.IsOptional.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 373 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

                tupleDelim = ",";
            }
            if (Context.CurrentClass.PricingParameter () != null && Context.CurrentClass.Name == method.Name)
            {

            
            #line default
            #line hidden
            this.Write("                    , Generator.ValueTuple (QL_Pricer, false)\r\n");
            
            #line 380 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            
            }

            
            #line default
            #line hidden
            this.Write("                \r\n                    };\r\n                \r\n");
            
            #line 385 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            if (method.Name == Context.CurrentClass.Name)
            {

            
            #line default
            #line hidden
            this.Write("                return \"");
            
            #line 389 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace.Replace(".Data", ".Fun") + "." + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Create \" +\r\n                    \"(\" + Generator.ParameterSource (typeof(");
            
            #line 390 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace.Replace(".Data", ".QL") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("_Factory), \"Create\", __v) + \")\";\r\n");
            
            #line 391 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write(@"                if (With != null)
                {
                    if (With is IPreCell)
                    {
                        IPreCell pre = (IPreCell) With;
                        if (With is IPostCell)
                        {
                            IPostCell post = (IPostCell) With;
                            return post.AfterSource (pre.BeforeSource (Generator.LetMnemonic (");
            
            #line 404 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Mnemonic), \".Value.");
            
            #line 404 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" \" + \r\n                                \"(\" + Generator.ParameterSource (typeof(");
            
            #line 405 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace.Replace(".Data", ".QL") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("), \"");
            
            #line 405 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" \", __v) + \")\"));\r\n                        }\r\n                        else\r\n     " +
                    "                       return pre.BeforeSource (Generator.LetMnemonic (");
            
            #line 408 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Mnemonic), \"");
            
            #line 408 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" \" + \r\n                                \"(\" + Generator.ParameterSource (typeof(");
            
            #line 409 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace.Replace(".Data", ".QL") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("), \"");
            
            #line 409 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" \", __v) + \")\");\r\n                    }\r\n                    else if (With is IPo" +
                    "stCell)\r\n                    {\r\n                        IPostCell post = (IPostC" +
                    "ell) With;\r\n                        return post.AfterSource (Generator.LetMnemon" +
                    "ic (");
            
            #line 414 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Mnemonic) + \".Value.");
            
            #line 414 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            
            #line 414 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("(" + method.GetCellParamCall ("", "", ",") + ")"));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    }\r\n                }\r\n                return Generator.L" +
                    "etMnemonic (");
            
            #line 417 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".Mnemonic) + \".Value.");
            
            #line 417 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" \" + \r\n                    \"(\" + Generator.ParameterSource (typeof(");
            
            #line 418 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace.Replace(".Data", ".QL") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("), \"");
            
            #line 418 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.UpperName));
            
            #line default
            #line hidden
            this.Write(" \", __v) + \")\";\r\n");
            
            #line 419 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n   \r\n");
            
            #line 426 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\r\n        [CollectionDataContract (Name = \"");
            
            #line 431 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataNamespace + "." + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".CellVector\", Namespace = Declarations.SchemaVersion)]\r\n        [ShowWith (typeof" +
                    " (ShowableVector<");
            
            #line 432 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        [CellProxy (typeof(CellProxy<IVector<");
            
            #line 433 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>))]\r\n        public class CellVector : CoCellVector<");
            
            #line 434 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n        {\r\n            public CellVector () : base () { }\r\n            public " +
                    "CellVector (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }\r\n     " +
                    "       public CellVector (IModel parent, string Mnemonic, IEnumerable<ICoCell<");
            
            #line 438 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">> e) : base (parent, Mnemonic, e) { }\r\n            public CellVector (IModel par" +
                    "ent, IEnumerable<ICoCell<");
            
            #line 439 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">> e)\r\n                : base (e)\r\n            {\r\n                _parent = paren" +
                    "t;\r\n            }\r\n            public CellVector (IModel parent, INativeVector<I" +
                    "CoCell<");
            
            #line 444 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(@">> n)
                : base (n)
            {
                _parent = parent;
            }
            // XL creation interface
            public CellVector (IModel model, object[] objects)
                : base ()
            {
                _parent = model;
                _mnemonic = (string) objects.GetValue (0);
                IEnumerable os = (IEnumerable) objects.GetValue (1);
    
                foreach (object o in os)
                {
                    var v = CellHelper.CellObject<");
            
            #line 459 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(@"> (model, o);
                    Add(v);
                    v.Change += OnChange;
                }
            }
            public override string ToString ()
            {
                return Generator.EnumerationSource (this);
            }
        }
    
        [CollectionDataContract (Name = """);
            
            #line 470 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataNamespace + "." + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".CellMatrix\", Namespace = Declarations.SchemaVersion)]\r\n        [ShowWith (typeof" +
                    " (ShowableMatrix<");
            
            #line 471 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        [CellProxy (typeof(CellProxy<IMatrix<");
            
            #line 472 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>))]\r\n        public class CellMatrix : CoCellMatrix<");
            
            #line 473 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n        {\r\n            public CellMatrix () : base () { }\r\n            public " +
                    "CellMatrix (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }\r\n     " +
                    "       public CellMatrix (IModel parent, string Mnemonic, IEnumerable<IEnumerabl" +
                    "e<ICoCell<");
            
            #line 477 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(@">>> e) : base (parent, Mnemonic, e) { }
            // XL creation infterface
            public CellMatrix (IModel model, object[] objects)
                : base ()
            {
                _parent = model;
                _mnemonic = (string) objects.GetValue (0);
                IEnumerable os = (IEnumerable) objects.GetValue (1);
    
                foreach (object o in os)
                {
                    var v = CellHelper.CellVector<");
            
            #line 488 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">(model, o);\r\n                    Add (v);\r\n                    v.Change += OnCha" +
                    "nge;\r\n                }\r\n            }\r\n            public CellMatrix (IModel pa" +
                    "rent, IEnumerable<IEnumerable<ICoCell<");
            
            #line 493 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>> e)\r\n                : base (e)\r\n            {\r\n                _parent = pare" +
                    "nt;\r\n            }\r\n            public CellMatrix (IModel parent, INativeMatrix<" +
                    "ICoCell<");
            
            #line 498 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">> nv)\r\n                : base (nv)\r\n            {\r\n                _parent = par" +
                    "ent;\r\n            }\r\n    \r\n            protected override CoCellVector<");
            
            #line 504 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("> CreateCellVector (IEnumerable<ICoCell<");
            
            #line 504 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">> source)\r\n            {\r\n                return new CellVector (_parent, source" +
                    ");\r\n            }\r\n            protected override CoCellVector<");
            
            #line 508 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("> CreateCellVector (INativeVector<ICoCell<");
            
            #line 508 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">> nv)\r\n            {\r\n                return new CellVector (_parent, nv);\r\n    " +
                    "        }\r\n            protected override CoCellVector<");
            
            #line 512 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(@"> CreateCellVector ()
            {
                return new CellVector ();
            }
            public override string ToString ()
            {
                return Generator.EnumerationSource (this);
            }
        }
    
        [CollectionDataContract (Name = """);
            
            #line 522 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataNamespace + "." + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(".CellCube\", Namespace = Declarations.SchemaVersion)]\r\n        [ShowWith (typeof (" +
                    "ShowableCube<");
            
            #line 523 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">))]\r\n        [CellProxy (typeof(CellProxy<ICube<");
            
            #line 524 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>))]\r\n        public class CellCube : CoCellCube<");
            
            #line 525 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(@">
        {
            public CellCube () : base () { }
            public CellCube (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }
            public CellCube (IModel parent, string Mnemonic, IEnumerable<IEnumerable<IEnumerable<ICoCell<");
            
            #line 529 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(@">>>> e) : base (parent, Mnemonic, e) { }
            // XL creation infterface
            public CellCube (IModel model, object[] objects)
                : base ()
            {
                _parent = model;
                _mnemonic = (string) objects.GetValue (0);
                IEnumerable os = (IEnumerable) objects.GetValue (1);
    
                foreach (object o in os)
                {
                    if (o is IMatrix<ICoCell<");
            
            #line 540 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>)\r\n                    {\r\n                        Add ((IMatrix<ICoCell<");
            
            #line 542 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>) o);\r\n                    }\r\n                    else\r\n                    {\r\n" +
                    "                        Add (new CellMatrix (model, \"\", (IEnumerable<IEnumerable" +
                    "<ICoCell<");
            
            #line 546 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>>) o));\r\n                    }\r\n                }\r\n            }\r\n            p" +
                    "ublic CellCube (IModel parent, IEnumerable<IEnumerable<IEnumerable<ICoCell<");
            
            #line 550 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>>> e)\r\n                : base (e)\r\n            {\r\n                _parent = par" +
                    "ent;\r\n            }\r\n            public CellCube (IModel parent, INativeCube<ICo" +
                    "Cell<");
            
            #line 555 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">> nv)\r\n                : base (nv)\r\n            {\r\n                _parent = par" +
                    "ent;\r\n            }\r\n            protected override CoCellMatrix<");
            
            #line 560 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("> CreateCellMatrix (IEnumerable<IEnumerable<ICoCell<");
            
            #line 560 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">>> source)\r\n            {\r\n                return new CellMatrix (_parent, sourc" +
                    "e);\r\n            }\r\n            protected override CoCellMatrix<");
            
            #line 564 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("> CreateCellMatrix (INativeMatrix<ICoCell<");
            
            #line 564 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write(">> nv)\r\n            {\r\n                return new CellMatrix (_parent, nv);\r\n    " +
                    "        }\r\n            protected override CoCellMatrix<");
            
            #line 568 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("> CreateCellMatrix ()\r\n            {\r\n                return new CellMatrix ();\r\n" +
                    "            }\r\n            protected override CoCellVector<");
            
            #line 572 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.CurrentClass.GetNamespace(".").Replace("::", ".") + ".I" + Context.CurrentClass.Name));
            
            #line default
            #line hidden
            this.Write("> CreateCellVector ()\r\n            {\r\n                return new CellVector ();\r\n" +
                    "            }\r\n            public override string ToString ()\r\n            {\r\n  " +
                    "              return Generator.EnumerationSource (this);\r\n            }\r\n       " +
                    " }\r\n    }\r\n}\r\n");
            
            #line 583 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"
  
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 584 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

		public Context Context = new Context();

		public Class
			( string ElementName
			, string RootPackageName
			)
		{
			_ElementNameField = ElementName;
			_RootPackageNameField = RootPackageName;
		}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\steve\source\repos\Cephei2\Cephei.Gen\Data\Class.tt"

private string _ElementNameField;

/// <summary>
/// Access the ElementName parameter of the template.
/// </summary>
private string ElementName
{
    get
    {
        return this._ElementNameField;
    }
}

private string _RootPackageNameField;

/// <summary>
/// Access the RootPackageName parameter of the template.
/// </summary>
private string RootPackageName
{
    get
    {
        return this._RootPackageNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ElementNameValueAcquired = false;
if (this.Session.ContainsKey("ElementName"))
{
    this._ElementNameField = ((string)(this.Session["ElementName"]));
    ElementNameValueAcquired = true;
}
if ((ElementNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ElementName");
    if ((data != null))
    {
        this._ElementNameField = ((string)(data));
    }
}
bool RootPackageNameValueAcquired = false;
if (this.Session.ContainsKey("RootPackageName"))
{
    this._RootPackageNameField = ((string)(this.Session["RootPackageName"]));
    RootPackageNameValueAcquired = true;
}
if ((RootPackageNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("RootPackageName");
    if ((data != null))
    {
        this._RootPackageNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ClassBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
