// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cephei.Gen
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DataCollection : DataCollectionBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n\r\n");
            
            #line 6 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
/*
Name:
Author: 
Description: 
*/
            
            #line default
            #line hidden
            this.Write("using System.Collections.Generic;\r\nusing System.Runtime.Serialization;\r\nusing Cep" +
                    "hei.Core;\r\nusing Cephei.Core.Generic;\r\nusing Cephei.Kernel;\r\nusing System.Collec" +
                    "tions;\r\nusing System;\r\n\r\nnamespace Cephei.Data\r\n{\r\n    [DataContract (Name = \"");
            
            #line 26 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("\", Namespace = Declarations.SchemaVersion)]\r\n    [ShowWith (typeof (ShowableValue" +
                    "))]\r\n    [CellProxy (typeof(CellProxy<");
            
            #line 28 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">))]\r\n    public class ");
            
            #line 29 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cell : Cell<");
            
            #line 29 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> \r\n    {\r\n        public ");
            
            #line 31 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cell () : base () { }\r\n        public ");
            
            #line 32 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cell (");
            
            #line 32 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(" v) : base (v) { }\r\n        public ");
            
            #line 33 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cell (");
            
            #line 33 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(" v, string Mnemonic) : base (v, Mnemonic) { }\r\n        public ");
            
            #line 34 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cell (");
            
            #line 34 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(" v, string Mnemonic, IModel model) : base (v, Mnemonic, model) { }\r\n        publi" +
                    "c ");
            
            #line 35 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cell (IModel model, object[] objects)\r\n        {\r\n            _parent = model;\r\n " +
                    "           _mnemonic = (string) objects.GetValue (0);\r\n            Content = (");
            
            #line 39 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(") objects.GetValue (1);\r\n        }\r\n    }\r\n\r\n    [CollectionDataContract (Name = " +
                    "\"");
            
            #line 43 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector\", Namespace = Declarations.SchemaVersion)]\r\n    [ShowWith (typeof (Showabl" +
                    "eVector<");
            
            #line 44 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">))]\r\n    [CellProxy (typeof(CellProxy<IVector<");
            
            #line 45 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>))]\r\n    public class ");
            
            #line 46 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector : CoVector<");
            
            #line 46 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 48 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector () : base () { }\r\n        public ");
            
            #line 49 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }\r\n        pu" +
                    "blic ");
            
            #line 50 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector (IModel parent, string Mnemonic, IEnumerable<");
            
            #line 50 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> e) : base (parent, Mnemonic, e) { }\r\n        public ");
            
            #line 51 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector (IModel parent, IEnumerable<");
            
            #line 51 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> e)\r\n            : base (e)\r\n        {\r\n            _parent = parent;\r\n        }" +
                    "\r\n        public ");
            
            #line 56 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector (IModel parent, INativeVector<");
            
            #line 56 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> n)\r\n            : base (n)\r\n        {\r\n            _parent = parent;\r\n        }" +
                    "\r\n        // XL creation interface\r\n        public ");
            
            #line 62 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector (IModel model, object[] objects)\r\n            : base ()\r\n        {\r\n      " +
                    "      _parent = model;\r\n            _mnemonic = (string) objects.GetValue (0);\r\n" +
                    "            ");
            
            #line 67 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("[] arr = (");
            
            #line 67 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(@"[]) objects.GetValue (1);
            this.Capacity = arr.Length;
            AddRange (arr);
        }
        public override string ToString ()
        {
            return Generator.EnumerationSource (this);
        }
    }
    [CollectionDataContract (Name = """);
            
            #line 76 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector\", ItemName=\"i\", Namespace = Declarations.SchemaVersion)]\r\n    [ShowWit" +
                    "h (typeof (ShowableVector<");
            
            #line 77 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">))]\r\n    [CellProxy (typeof(CellProxy<IVector<");
            
            #line 78 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>))]\r\n    public class ");
            
            #line 79 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector : CoCellVector<");
            
            #line 79 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 81 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector () : base () { }\r\n        public ");
            
            #line 82 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }\r\n      " +
                    "  public ");
            
            #line 83 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector (IModel parent, string Mnemonic, IEnumerable<ICoCell<");
            
            #line 83 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> e) : base (parent, Mnemonic, e) { }\r\n        public ");
            
            #line 84 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector (IModel parent, IEnumerable<ICoCell<");
            
            #line 84 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> e)\r\n            : base (e)\r\n        {\r\n            _parent = parent;\r\n        " +
                    "}\r\n        public ");
            
            #line 89 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector (IModel parent, INativeVector<ICoCell<");
            
            #line 89 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> n)\r\n            : base (n)\r\n        {\r\n            _parent = parent;\r\n        " +
                    "}\r\n        // XL creation interface\r\n        public ");
            
            #line 95 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write(@"CellVector (IModel model, object[] objects)
            : base ()
        {
            _parent = model;
            _mnemonic = (string) objects.GetValue (0);
            IEnumerable os = (IEnumerable) objects.GetValue (1);

            foreach (object o in os)
            {
                var v = CellHelper.CellObject<");
            
            #line 104 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> (model, o, p => new ");
            
            #line 104 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write(@"Cell (p));
                Add(v);
                v.Change += OnChange;
            }
        }
        public override string ToString ()
        {
            return Generator.EnumerationSource (this);
        }
    }

    [CollectionDataContract (Name = ""Cephei.Data.");
            
            #line 115 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix\", Namespace = Declarations.SchemaVersion)]\r\n    [ShowWith (typeof (Showabl" +
                    "eMatrix<");
            
            #line 116 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">))]\r\n    [CellProxy(typeof(CellProxy<IMatrix<");
            
            #line 117 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>))]\r\n    public class ");
            
            #line 118 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix : CoMatrix<");
            
            #line 118 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 120 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix () : base () { }\r\n        public ");
            
            #line 121 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }\r\n        pu" +
                    "blic ");
            
            #line 122 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix (IModel parent, string Mnemonic, IEnumerable<IEnumerable<");
            
            #line 122 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> e) : base (parent, Mnemonic, e) { }\r\n        // XL creation infterface\r\n      " +
                    "  public ");
            
            #line 124 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write(@"Matrix (IModel model, object[] objects)
            : base ()
        {
            _parent = model;
            _mnemonic = (string) objects.GetValue (0);
            IEnumerable os = (IEnumerable) objects.GetValue (1);

            foreach (object o in os)
            {
                if (o is IVector<");
            
            #line 133 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">)\r\n                {\r\n                    Add ((IVector<");
            
            #line 135 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">) o);\r\n                }\r\n                else\r\n                {\r\n             " +
                    "       Add (new ");
            
            #line 139 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector (model, (IEnumerable<");
            
            #line 139 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">) o));\r\n                }\r\n            }\r\n        }\r\n        public ");
            
            #line 143 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix (IModel parent, IEnumerable<IEnumerable<");
            
            #line 143 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> e)\r\n            : base (e)\r\n        {\r\n            _parent = parent;\r\n        " +
                    "}\r\n        public ");
            
            #line 148 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix (IModel parent, INativeMatrix<");
            
            #line 148 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> nv)\r\n            : base (nv)\r\n        {\r\n            _parent = parent;\r\n       " +
                    " }\r\n\r\n        protected override CoVector<");
            
            #line 154 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateVector (IEnumerable<");
            
            #line 154 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> source)\r\n        {\r\n            return new ");
            
            #line 156 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector (_parent, source);\r\n        }\r\n        protected override CoVector<");
            
            #line 158 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateVector (INativeVector<");
            
            #line 158 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> nv)\r\n        {\r\n            return new  ");
            
            #line 160 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector (_parent, nv);\r\n        }\r\n        protected override CoVector<");
            
            #line 162 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateVector ()\r\n        {\r\n            return new ");
            
            #line 164 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector ();\r\n        }\r\n        public override string ToString ()\r\n        {\r\n   " +
                    "         return Generator.EnumerationSource (this);\r\n        }\r\n    }\r\n    [Coll" +
                    "ectionDataContract (Name = \"");
            
            #line 171 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix\", Namespace = Declarations.SchemaVersion)]\r\n    [ShowWith (typeof (Sho" +
                    "wableMatrix<");
            
            #line 172 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">))]\r\n    [CellProxy(typeof(CellProxy<IMatrix<");
            
            #line 173 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>))]\r\n    public class ");
            
            #line 174 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix : CoCellMatrix<");
            
            #line 174 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 176 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix () : base () { }\r\n        public ");
            
            #line 177 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }\r\n      " +
                    "  public ");
            
            #line 178 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix (IModel parent, string Mnemonic, IEnumerable<IEnumerable<ICoCell<");
            
            #line 178 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>> e) : base (parent, Mnemonic, e) { }\r\n        // XL creation infterface\r\n     " +
                    "   public ");
            
            #line 180 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write(@"CellMatrix (IModel model, object[] objects)
            : base ()
        {
            _parent = model;
            _mnemonic = (string) objects.GetValue (0);
            IEnumerable os = (IEnumerable) objects.GetValue (1);

            foreach (object o in os)
            {
                var v = CellHelper.CellVector<");
            
            #line 189 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">(model, o);\r\n                Add (v);\r\n                v.Change += OnChange;\r\n  " +
                    "          }\r\n        }\r\n        public ");
            
            #line 194 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix (IModel parent, IEnumerable<IEnumerable<ICoCell<");
            
            #line 194 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>> e)\r\n            : base (e)\r\n        {\r\n            _parent = parent;\r\n       " +
                    " }\r\n        public ");
            
            #line 199 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix (IModel parent, INativeMatrix<ICoCell<");
            
            #line 199 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> nv)\r\n            : base (nv)\r\n        {\r\n            _parent = parent;\r\n      " +
                    "  }\r\n\r\n        protected override CoCellVector<");
            
            #line 205 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateCellVector (IEnumerable<ICoCell<");
            
            #line 205 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> source)\r\n        {\r\n            return new ");
            
            #line 207 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector (_parent, source);\r\n        }\r\n        protected override CoCellVector" +
                    "<");
            
            #line 209 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateCellVector (INativeVector<ICoCell<");
            
            #line 209 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> nv)\r\n        {\r\n            return new  ");
            
            #line 211 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector (_parent, nv);\r\n        }\r\n        protected override CoCellVector<");
            
            #line 213 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateCellVector ()\r\n        {\r\n            return new ");
            
            #line 215 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector ();\r\n        }\r\n        public override string ToString ()\r\n        {\r" +
                    "\n            return Generator.EnumerationSource (this);\r\n        }\r\n    }\r\n\r\n   " +
                    " [CollectionDataContract (Name = \"");
            
            #line 223 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cube\", Namespace = Declarations.SchemaVersion)]\r\n    [ShowWith (typeof (ShowableC" +
                    "ube<");
            
            #line 224 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">))]\r\n    [CellProxy(typeof(CellProxy<ICube<double>>))]\r\n    public class ");
            
            #line 226 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cube : CoCube<");
            
            #line 226 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 228 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cube () : base () { }\r\n        public ");
            
            #line 229 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cube (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }\r\n        publ" +
                    "ic ");
            
            #line 230 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Cube (IModel parent, string Mnemonic, IEnumerable<IEnumerable<IEnumerable<");
            
            #line 230 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>> e) : base (parent, Mnemonic, e) { }\r\n        // XL creation infterface\r\n     " +
                    "   public ");
            
            #line 232 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write(@"Cube (IModel model, object[] objects)
            : base ()
        {
            _parent = model;
            _mnemonic = (string) objects.GetValue (0);
            IEnumerable os = (IEnumerable) objects.GetValue (1);

            foreach (object o in os)
            {
                Add ((IMatrix<");
            
            #line 241 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">)CellHelper.CellMatrix<");
            
            #line 241 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">(model, o));\r\n            }\r\n        }\r\n        protected override CoMatrix<");
            
            #line 244 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateMatrix (IEnumerable<IEnumerable<");
            
            #line 244 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> source)\r\n        {\r\n            return new ");
            
            #line 246 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix (_parent, source);\r\n        }\r\n        protected override CoMatrix<");
            
            #line 248 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateMatrix (INativeMatrix<");
            
            #line 248 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> nv)\r\n        {\r\n            return new ");
            
            #line 250 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix (_parent, nv);\r\n        }\r\n        protected override CoMatrix<");
            
            #line 252 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateMatrix ()\r\n        {\r\n            return new ");
            
            #line 254 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Matrix ();\r\n        }\r\n        protected override CoVector<");
            
            #line 256 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateVector ()\r\n        {\r\n            return new ");
            
            #line 258 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("Vector ();\r\n        }\r\n        public override string ToString ()\r\n        {\r\n   " +
                    "         return Generator.EnumerationSource (this);\r\n        }\r\n    }\r\n    [Coll" +
                    "ectionDataContract (Name = \"Cephei.Data.");
            
            #line 265 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellCube\", Namespace = Declarations.SchemaVersion)]\r\n    [ShowWith (typeof (Showa" +
                    "bleCube<");
            
            #line 266 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">))]\r\n    [CellProxy(typeof(CellProxy<ICube<");
            
            #line 267 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>))]\r\n    public class ");
            
            #line 268 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellCube : CoCellCube<");
            
            #line 268 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 270 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellCube () : base () { }\r\n        public ");
            
            #line 271 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellCube (IModel parent, string Mnemonic) : base (parent, Mnemonic) { }\r\n        " +
                    "public ");
            
            #line 272 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellCube (IModel parent, string Mnemonic, IEnumerable<IEnumerable<IEnumerable<ICo" +
                    "Cell<");
            
            #line 272 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>>> e) : base (parent, Mnemonic, e) { }\r\n        // XL creation infterface\r\n    " +
                    "    public ");
            
            #line 274 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write(@"CellCube (IModel model, object[] objects)
            : base ()
        {
            _parent = model;
            _mnemonic = (string) objects.GetValue (0);
            IEnumerable os = (IEnumerable) objects.GetValue (1);

            foreach (object o in os)
            {
                var v = CellHelper.CellMatrix<");
            
            #line 283 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">(model, o);\r\n                Add(v);\r\n                v.Change += OnChange;\r\n   " +
                    "         }\r\n        }\r\n        public ");
            
            #line 288 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellCube (IModel parent, IEnumerable<IEnumerable<IEnumerable<ICoCell<");
            
            #line 288 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>>> e)\r\n            : base (e)\r\n        {\r\n            _parent = parent;\r\n      " +
                    "  }\r\n        public ");
            
            #line 293 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellCube (IModel parent, INativeCube<ICoCell<");
            
            #line 293 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> nv)\r\n            : base (nv)\r\n        {\r\n            _parent = parent;\r\n      " +
                    "  }\r\n        protected override CoCellMatrix<");
            
            #line 298 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateCellMatrix (IEnumerable<IEnumerable<ICoCell<");
            
            #line 298 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">>> source)\r\n        {\r\n            return new ");
            
            #line 300 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix (_parent, source);\r\n        }\r\n        protected override CoCellMatrix" +
                    "<");
            
            #line 302 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateCellMatrix (INativeMatrix<ICoCell<");
            
            #line 302 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write(">> nv)\r\n        {\r\n            return new ");
            
            #line 304 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix (_parent, nv);\r\n        }\r\n        protected override CoCellMatrix<");
            
            #line 306 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateCellMatrix ()\r\n        {\r\n            return new ");
            
            #line 308 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellMatrix ();\r\n        }\r\n        protected override CoCellVector<");
            
            #line 310 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeCode));
            
            #line default
            #line hidden
            this.Write("> CreateCellVector ()\r\n        {\r\n            return new ");
            
            #line 312 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Mnemonic));
            
            #line default
            #line hidden
            this.Write("CellVector ();\r\n        }\r\n        public override string ToString ()\r\n        {\r" +
                    "\n            return Generator.EnumerationSource (this);\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 320 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"

	public DataCollection 
		( string Mnemonic 
		, string typeCode
		, int msgNo
		)
	{
		_MnemonicField = Mnemonic;
        _TypeCodeField = typeCode;
        _MsgNoField = msgNo;
	}


        
        #line default
        #line hidden
        
        #line 1 "C:\Users\steve\Source\Repos\Cephei2\Cephei.Gen\Data\DataCollection.tt"

private string _MnemonicField;

/// <summary>
/// Access the Mnemonic parameter of the template.
/// </summary>
private string Mnemonic
{
    get
    {
        return this._MnemonicField;
    }
}

private string _TypeCodeField;

/// <summary>
/// Access the TypeCode parameter of the template.
/// </summary>
private string TypeCode
{
    get
    {
        return this._TypeCodeField;
    }
}

private int _MsgNoField;

/// <summary>
/// Access the MsgNo parameter of the template.
/// </summary>
private int MsgNo
{
    get
    {
        return this._MsgNoField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool MnemonicValueAcquired = false;
if (this.Session.ContainsKey("Mnemonic"))
{
    this._MnemonicField = ((string)(this.Session["Mnemonic"]));
    MnemonicValueAcquired = true;
}
if ((MnemonicValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Mnemonic");
    if ((data != null))
    {
        this._MnemonicField = ((string)(data));
    }
}
bool TypeCodeValueAcquired = false;
if (this.Session.ContainsKey("TypeCode"))
{
    this._TypeCodeField = ((string)(this.Session["TypeCode"]));
    TypeCodeValueAcquired = true;
}
if ((TypeCodeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TypeCode");
    if ((data != null))
    {
        this._TypeCodeField = ((string)(data));
    }
}
bool MsgNoValueAcquired = false;
if (this.Session.ContainsKey("MsgNo"))
{
    this._MsgNoField = ((int)(this.Session["MsgNo"]));
    MsgNoValueAcquired = true;
}
if ((MsgNoValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("MsgNo");
    if ((data != null))
    {
        this._MsgNoField = ((int)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DataCollectionBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
